import React from 'react';
import Page from '../../Page';

const ChartALoad = () => (
  <Page>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas aliquet rhoncus turpis eget congue. Cras congue est id eros egestas volutpat. Sed ac purus orci. Phasellus dolor orci, auctor quis vestibulum ac, feugiat lacinia sapien. Praesent sed est ante. Curabitur nec fermentum massa, sit amet hendrerit ipsum. Aliquam euismod tincidunt lorem non ornare. Aliquam eget porta enim. Curabitur vel vulputate tortor. Proin ex justo, gravida et vehicula id, tincidunt a erat. Ut a metus eu justo pretium tempor sed id nunc. Cras ac viverra purus. Morbi rhoncus posuere suscipit.</p>
    <p>Quisque vehicula sed enim eu ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris at augue eu velit scelerisque ultrices. Donec lectus ligula, tincidunt ac risus eu, convallis fringilla elit. Vestibulum venenatis metus iaculis urna tincidunt mattis. Integer non turpis scelerisque ante blandit accumsan aliquam vel ante. Pellentesque volutpat lobortis nisl id blandit. Ut pretium, magna et ullamcorper viverra, mauris risus gravida quam, eget bibendum neque mauris sed lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur non tellus vitae quam finibus porta vel et ligula. Aliquam et ultrices mi, eget ullamcorper mauris. Curabitur ut nisl ultricies, commodo arcu vulputate, posuere tortor. Nulla eget nunc sit amet lectus malesuada facilisis at et quam. Nam sit amet sollicitudin nisi.</p>
    <p>Aenean vel finibus risus, nec gravida elit. Nunc pulvinar id tortor non viverra. Proin eget nibh ipsum. Nullam ac sapien hendrerit, sollicitudin tellus in, imperdiet orci. In gravida porttitor lacus, sit amet mollis risus tempor at. Sed lorem sapien, tempor non pellentesque ac, imperdiet nec neque. Integer eleifend molestie justo, at dictum ligula egestas vitae. Vivamus porttitor posuere risus nec cursus.</p>
    <p>Nulla nunc erat, sollicitudin eget porttitor ac, suscipit vitae lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi mattis congue ex, vitae tristique enim accumsan eget. Sed sodales vitae mauris eget condimentum. In posuere, libero nec aliquam interdum, urna mi dictum odio, iaculis laoreet nisi velit ut odio. In a dapibus odio, eu iaculis enim. Aenean lacinia leo in est pharetra vehicula. Etiam aliquam eleifend mauris sit amet rutrum. Etiam fermentum porta dapibus. Maecenas cursus lacus ligula, sit amet cursus odio interdum sit amet. Etiam nec augue pretium, maximus libero a, vulputate enim.</p>
    <p>Fusce nec neque id mi molestie cursus in egestas magna. Morbi vel viverra eros. In sodales efficitur magna, sed auctor mi ultrices nec. In hac habitasse platea dictumst. Proin ut risus eleifend, euismod neque quis, bibendum risus. Integer sapien lectus, sodales ut pulvinar a, eleifend nec lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ullamcorper velit tortor, ac ornare velit fringilla et. Duis egestas finibus ante, sed semper leo. Aliquam quis venenatis risus, sit amet sodales nisl. Fusce ipsum neque, placerat a tellus sed, molestie consectetur felis. Aliquam molestie vel est ut gravida. Aliquam vel odio rhoncus, scelerisque turpis id, ultricies felis. Vestibulum ullamcorper mauris diam. Pellentesque tincidunt ligula in ligula lacinia tempus.</p>
    <p>Aliquam vitae erat vel sem sodales commodo non laoreet lectus. Nullam a faucibus quam. Curabitur vulputate blandit tortor tincidunt ullamcorper. Nunc vehicula quam non ipsum tempus pulvinar. Proin fringilla, nulla a rhoncus condimentum, massa purus vulputate felis, quis volutpat risus massa a eros. Integer tempor vestibulum pellentesque. Mauris sit amet dignissim lorem. Suspendisse potenti. Proin egestas posuere erat eget aliquet. Vivamus sapien justo, ornare vel tincidunt quis, sagittis ac dui. Aenean varius nisl sed nisl sodales, non dapibus dolor sagittis. Duis commodo diam nec ipsum condimentum, ac pretium orci finibus. Ut dapibus nulla ipsum, eget vehicula purus vestibulum quis. Fusce lacinia lectus vel cursus ullamcorper. Donec ac ante quis lectus pretium gravida. Vivamus massa nulla, malesuada ac quam quis, finibus dapibus orci.</p>
    <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur auctor accumsan nibh, quis dictum dui malesuada ac. Suspendisse tristique sed erat id gravida. Proin commodo volutpat leo, non laoreet risus efficitur quis. Etiam ex ante, dictum vitae convallis ut, faucibus sed tortor. Nunc egestas nisi sit amet ipsum pulvinar, eu auctor nunc hendrerit. Cras eget nibh lacinia lacus rutrum rhoncus in vitae ex. Mauris id massa at tortor volutpat semper eu ut augue. Nulla ut ultrices justo, non dictum lorem.</p>
    <p>Nam mattis mauris vel felis gravida, a cursus magna sodales. Proin mi lectus, feugiat ut maximus at, vulputate eu lectus. Nunc interdum porttitor consequat. Etiam dui elit, dapibus et nisi at, facilisis lacinia nisi. Nunc id metus vitae nibh pulvinar pharetra. Sed vulputate enim elit, a blandit lectus facilisis id. Vestibulum diam quam, efficitur eu ultricies in, suscipit vitae lorem. Phasellus sagittis neque sed est iaculis eleifend. Maecenas vitae mi id lorem efficitur bibendum. Integer finibus sem a orci efficitur aliquam. Suspendisse vestibulum tristique pharetra. Proin a diam lectus. Proin aliquet risus eu laoreet condimentum. Proin tempor elementum arcu ut suscipit. Vivamus velit eros, rhoncus ut varius eget, ullamcorper non augue. Donec ultrices, diam et maximus facilisis, risus odio sagittis elit, at hendrerit eros nisl non neque.</p>
    <p>Vivamus eu ex enim. Ut accumsan elementum nisi nec tempus. Aliquam eget feugiat ligula. Proin euismod ornare urna, eu commodo purus vulputate non. Curabitur consectetur, metus egestas tincidunt luctus, dui metus ultrices lacus, id tincidunt lorem turpis eu libero. Nulla facilisi. Vivamus a ultricies purus. Praesent placerat, ligula at finibus tincidunt, tortor ex malesuada nisi, quis pellentesque massa mi et risus.</p>
    <p>Integer sit amet sodales augue, nec efficitur nisl. Quisque sagittis mi ut libero vulputate, nec rhoncus sapien tristique. Curabitur scelerisque odio eros, sit amet commodo ex euismod non. Aenean et congue justo, vel gravida dolor. Nunc libero tellus, eleifend vitae velit quis, cursus aliquam nisi. Donec commodo consectetur gravida. Sed sollicitudin justo ipsum, ac luctus lorem placerat vel. Pellentesque ac eros sed erat viverra dignissim. Sed vel augue nec nisi varius fringilla. Cras posuere nunc nec tortor hendrerit, in laoreet sem egestas. Vestibulum non ex consequat, egestas orci non, rhoncus arcu. Mauris sed odio accumsan nisl aliquet tincidunt.</p>
  </Page>
);

export default ChartALoad;
